name: Rust

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:

permissions:
  contents: write

jobs:
  check-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: actions/checkout@v6
      - name: Format
        run: cargo fmt --all -- --check
      - name: Lint
        run: cargo clippy -- -D warnings
      - name: Run tests
        run: cargo test

  build-and-deploy:
    needs: [check-and-test]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-13
            TARGET: x86_64-apple-darwin
            CROSS: false

          - os: macos-latest
            TARGET: aarch64-apple-darwin
            CROSS: false

          - os: ubuntu-latest
            TARGET: x86_64-unknown-linux-musl
            CROSS: true

          - os: ubuntu-latest
            TARGET: aarch64-unknown-linux-musl
            CROSS: true

          - os: windows-latest
            TARGET: x86_64-pc-windows-msvc
            CROSS: true
            EXTENSION: .exe

    steps:
      - uses: actions/checkout@v6

      - name: Build binary (native)
        if: ${{ ! matrix.CROSS }}
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.TARGET }}
      - name: Build binary (native)
        if: ${{ ! matrix.CROSS }}
        run: cargo build --release --target ${{ matrix.TARGET }}

      - name: Build binary (cross)
        if: ${{ matrix.CROSS }}
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.TARGET }}
          args: "--release"

      - name: Archive binary
        shell: bash
        run: |
          BIN="viua-${{ matrix.TARGET }}${{ matrix.EXTENSION }}"
          cp "target/${{ matrix.TARGET }}/release/viua${{ matrix.EXTENSION }}" "$BIN"
          echo "artifact=$BIN" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifact }}
          path: ${{ env.artifact }}

      - uses: softprops/action-gh-release@v2
        name: Upload binaries to release
        with:
          files: ${{ env.artifact }}
